backend:
  name: github
  repo: kunj7076/jp_inter_collage
  branch: main
  base_url: https://decap-cms-oauth.vercel.app

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "notices"
    label: "Notice Board (सूचनाएं)"
    folder: "_data/notices"
    create: true
    extension: "json"
    format: "json"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Notice Text", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }

  - name: "gallery"
    label: "Photo Gallery (फोटो)"
    folder: "_data/gallery"
    create: true
    extension: "json"
    format: "json"
    fields:
      - { label: "Photo Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
